import Head from "next/head";
import Showcase from "@/components/home/Showcase";
import CategoryCards from "@/components/card/HomeCategoryCard";
const Home = () => {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <Showcase />
        <CategoryCards category={"Salat"} />
        <CategoryCards category={"Breakfast"} />
        <CategoryCards category={"Dessert"} />
      </main>
    </>
  );
};

export default Home;
